### ISSUE TITLE
PC started to burn

### ISSUE THREAD

**Issue by NULLYUKI** [PrincessAkira/Azariel-Client#3]
help

PC Specs:
Don't know they are all melting.

**Comment by HerXayah** [comment]
AMD Card

**Comment by NULLYUKI** [comment]
![1605973153_4xmcql4vexs51](https://user-images.githubusercontent.com/42326194/103904963-471e1080-50fe-11eb-85bc-8f362ff18cdb.png)

**Comment by NULLYUKI** [comment]
![EqbrkaDW4AEirD0](https://user-images.githubusercontent.com/42326194/105686686-d2b5e080-5ef7-11eb-9c29-bf17b5bd6230.jpg)

**Comment by NULLYUKI** [comment]
Chess be like
